# Homework
- https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/master/cohorts/2024/01-intro/homework.md
- https://courses.datatalks.club/ml-zoomcamp-2024/homework/hw01

In [ ]:
! pip install pandas numpy matplotlib seaborn

### Q1. Pandas version

In [3]:
import pandas as pd

In [4]:
pd.__version__

'2.2.3'

### Q2. Record count

How many records are in the dataset?

**Download dataset**

In [6]:
!curl -O https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  291k  100  291k    0     0   733k      0 --:--:-- --:--:-- --:--:--  741k


**Read data**

In [125]:
df_laptops = pd.read_csv('laptops.csv')

In [126]:
print(f'Dataset consist of {df_laptops.shape[0]} rows and {df_laptops.shape[1]} columns')

Dataset consist of 2160 rows and 12 columns


### Q3. Laptop brands

How many laptop brands are presented in the dataset?

In [127]:
df_laptops.describe(include='O').loc[['unique'],['Brand']]

Brand
unique    27

In [128]:
df_laptops.Brand.nunique()

27

### Q4. Missing values

How many columns in the dataset have missing values?

In [129]:
df_laptops.isnull().sum()[df_laptops.isnull().sum()>0]

Storage type      42
GPU             1371
Screen             4
dtype: int64

### Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

In [130]:
df_laptops[df_laptops['Brand']=='Dell']['Final Price'].max()

np.float64(3936.0)

### Q6. Median value of Screen
1. Find the median value of *Screen* column in the dataset.
1. Next, calculate the most frequent value of the same *Screen* column.
1. Use `fillna` method to fill the missing values in *Screen* column with the most frequent value from the previous step.
1. Now, calculate the median value of *Screen* once again.

In [131]:
df_laptops.Screen.median()

np.float64(15.6)

In [132]:
mfv = df_laptops.Screen.mode()[0]
mfv

np.float64(15.6)

Replace NaN with most frequent value (mode):

In [138]:
df_laptops.Screen = df_laptops.Screen.fillna(mfv)
df_laptops.Screen.median()

np.float64(15.6)

### Q7. Sum of weights
1. Select all the *"Innjoo"* laptops from the dataset.
1. Select only columns *RAM*, *Storage*, *Screen*.
1. Get the underlying NumPy array. Let's call it *X*.
1. Compute matrix-matrix multiplication between the transpose of *X* and *X*. To get the transpose, use X.T. Let's call the result *XTX*.
1. Compute the inverse of *XTX*.
1. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
1. Multiply the inverse of *XTX* with the transpose of *X*, and then multiply the result by y. Call the result w.
1. What's the sum of all the elements of the result?

In [145]:
X = df_laptops.loc[df_laptops.Brand=='Innjoo',['RAM', 'Storage', 'Screen']].values

In [146]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [151]:
XTX = X.dot(X.T)
XTX

array([[ 65843.36, 131379.36,  16635.96,  16651.96,  33035.96,  33035.96],
       [131379.36, 262451.36,  33019.96,  33035.96,  65803.96,  65803.96],
       [ 16635.96,  33019.96,   4310.81,   4318.81,   8414.81,   8414.81],
       [ 16651.96,  33035.96,   4318.81,   4330.81,   8426.81,   8426.81],
       [ 33035.96,  65803.96,   8414.81,   8426.81,  16618.81,  16618.81],
       [ 33035.96,  65803.96,   8414.81,   8426.81,  16618.81,  16618.81]])

In [148]:
X.T

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])